apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project-deployment
  labels:
    app: test-project-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-project-app
  template:
    metadata:
      labels:
        app: test-project-app
    spec:
      containers:
        - name: test-project-app
          image: shashank81jain/test-project
          ports:
            - containerPort: 80
